# Uncomment the next line to define a global platform for your project
use_frameworks!
inhibit_all_warnings!

target 'ChefCraftApp' do
  platform :ios, '13.0'
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for ChefCraftApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxMKMapView'
  pod 'Swinject'
  pod 'SwiftEntryKit'
  pod 'TBEmptyDataSet'
  pod 'RxRealm'
  pod 'RealmSwift'
  
  target 'ChefCraftAppTests' do
    inherit! :search_paths
    platform :ios, '13.0'

    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'RxNimble'
  end

end


