# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'ChefCraftApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChefCraftApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxRealm'
  pod 'Swinject'
  pod 'RealmSwift'
  pod 'ReachabilitySwift'

end
